import { Book } from '@/components/BookCard';
import { Category } from './components/CategoryFilter';

// 알라딘 API 기반 분야별 인기 도서 카테고리 및 세부 카테고리 데이터
export const categories: Category[] = [
  {
    id: 'all',
    name: '전체',
    color: '#E5E7EB',
    subcategories: [],
  },
  {
    id: 'humanities',
    name: '인문학',
    color: '#DBEAFE',
    subcategories: [
      { id: 'philosophy', name: '철학' },
      { id: 'psychology', name: '심리학' },
      { id: 'ethics', name: '윤리학' },
      { id: 'humanities-classics', name: '인문 고전' },
      { id: 'humanities-intro', name: '인문학 입문/해설' },
    ],
  },
  {
    id: 'literature',
    name: '문학',
    color: '#FCE7F3',
    subcategories: [
      { id: 'korean-literature', name: '한국문학' },
      { id: 'world-literature', name: '세계문학' },
      { id: 'classics', name: '고전문학' },
      { id: 'poetry', name: '시/시집' },
      { id: 'essays', name: '에세이' },
    ],
  },
  {
    id: 'history',
    name: '역사',
    color: '#FFEDD5',
    subcategories: [
      { id: 'korean-history', name: '한국사' },
      { id: 'world-history', name: '세계사' },
      { id: 'ancient-history', name: '고대사' },
      { id: 'modern-history', name: '근현대사' },
      { id: 'historical-figures', name: '역사인물' },
    ],
  },
  {
    id: 'social-science',
    name: '사회과학',
    color: '#D1FAE5',
    subcategories: [
      { id: 'politics', name: '정치/외교학' },
      { id: 'economics', name: '경제학' },
      { id: 'sociology', name: '사회학' },
      { id: 'education', name: '교육학' },
      { id: 'law', name: '법학' },
    ],
  },
  {
    id: 'natural-science',
    name: '자연과학',
    color: '#FEF3C7',
    subcategories: [
      { id: 'physics', name: '물리학' },
      { id: 'biology', name: '생명과학' },
      { id: 'astronomy', name: '천문학' },
      { id: 'mathematics', name: '수학' },
      { id: 'earth-science', name: '지구과학' },
    ],
  },
  {
    id: 'arts',
    name: '예술',
    color: '#E0E7FF',
    subcategories: [
      { id: 'fine-arts', name: '미술' },
      { id: 'music', name: '음악' },
      { id: 'performing-arts', name: '공연예술' },
      { id: 'architecture', name: '건축' },
      { id: 'photography', name: '사진' },
    ],
  },
  {
    id: 'religion',
    name: '종교',
    color: '#ECFCCB',
    subcategories: [
      { id: 'buddhism', name: '불교' },
      { id: 'christianity', name: '기독교' },
      { id: 'confucianism', name: '유교/도교' },
      { id: 'eastern-religion', name: '동양종교' },
      { id: 'mythology', name: '신화/설화' },
    ],
  },
];

// 실제 이미지를 사용한 도서 데이터
export const books: Book[] = [
  {
    id: 1,
    title: '모든 것의 기원',
    author: '데이비드 크리스티안',
    coverImage: '/images/book-covers/placeholder-1.jpg',
    category: 'philosophy',
    subcategory: 'western',
    rating: 4.8,
    reviews: 128,
    description:
      '소크라테스의 최후 변론을 담은 플라톤의 대화편. 철학의 기본을 담고 있는 고전 중의 고전.',
    publishDate: '2023-01-15',
    publisher: '고전출판사',
  },
  {
    id: 2,
    title: '사피엔스',
    author: '유발 하라리',
    coverImage: '/images/book-covers/placeholder-2.jpg',
    category: 'history',
    subcategory: 'world-history',
    rating: 4.7,
    reviews: 245,
    description:
      '인간의 죄의식과 구원을 탐구하는 도스토예프스키의 대표작. 라스콜리니코프의 심리 묘사가 탁월하다.',
    publishDate: '2023-02-20',
    publisher: '세계문학사',
  },
  {
    id: 3,
    title: '정의란 무엇인가',
    author: '마이클 샌델',
    coverImage: '/images/book-covers/placeholder-3.jpg',
    category: 'philosophy',
    subcategory: 'ethics',
    rating: 4.9,
    reviews: 356,
    description:
      '로마 제국의 번영과 쇠락을 다룬 역사서. 방대한 자료와 치밀한 분석이 돋보인다.',
    publishDate: '2023-03-10',
    publisher: '역사연구소',
  },
  {
    id: 4,
    title: '만들어진 신',
    author: '리처드 도킨스',
    coverImage: '/images/book-covers/placeholder-4.jpg',
    category: 'science',
    subcategory: 'biology',
    rating: 4.6,
    reviews: 98,
    description:
      '우주와 인간의 존재에 대한 과학적 탐구. 과학의 아름다움을 시적으로 표현한 명저.',
    publishDate: '2023-04-05',
    publisher: '과학세계',
  },
  {
    id: 5,
    title: '총, 균, 쇠',
    author: '재레드 다이아몬드',
    coverImage: '/images/book-covers/placeholder-5.jpg',
    category: 'history',
    subcategory: 'world-history',
    rating: 4.8,
    reviews: 214,
    description:
      '예술의 본질과 의미를 탐구한 톨스토이의 에세이. 예술의 사회적 역할에 대한 통찰력 있는 시각을 제공한다.',
    publishDate: '2023-05-12',
    publisher: '예술출판',
  },
  {
    id: 6,
    title: '이기적 유전자',
    author: '리처드 도킨스',
    coverImage: '/images/book-covers/placeholder-6.jpg',
    category: 'science',
    subcategory: 'biology',
    rating: 4.7,
    reviews: 178,
    description:
      '근대 경제학의 기초를 닦은 애덤 스미스의 역작. 시장 경제와 자유 무역의 원리를 설명한다.',
    publishDate: '2023-06-20',
    publisher: '경제연구소',
  },
  {
    id: 7,
    title: '코스모스',
    author: '칼 세이건',
    coverImage: '/images/book-covers/placeholder-7.jpg',
    category: 'science',
    subcategory: 'astronomy',
    rating: 4.9,
    reviews: 287,
    description:
      '행복과 덕성에 대한 아리스토텔레스의 철학적 탐구. 윤리학의 기본 틀을 제시한 고전.',
    publishDate: '2023-07-08',
    publisher: '고전출판사',
  },
  {
    id: 8,
    title: '국가란 무엇인가',
    author: '유시민',
    coverImage: '/images/book-covers/placeholder-8.jpg',
    category: 'social',
    subcategory: 'politics',
    rating: 4.5,
    reviews: 112,
    description:
      '전체주의 사회를 그린 디스토피아 소설. 감시와 통제, 그리고 자유의 의미를 생각하게 한다.',
    publishDate: '2023-08-15',
    publisher: '세계문학사',
  },
  {
    id: 9,
    title: '침묵의 봄',
    author: '레이첼 카슨',
    coverImage: '/images/book-covers/placeholder-9.jpg',
    category: 'social',
    subcategory: 'sociology',
    rating: 4.6,
    reviews: 143,
    description:
      '정치적 현실주의의 대표작. 권력과 통치에 대한 냉철한 분석이 담겨 있다.',
    publishDate: '2023-09-22',
    publisher: '정치학연구소',
  },
  {
    id: 10,
    title: '상대성이론',
    author: '알베르트 아인슈타인',
    coverImage:
      'https://image.aladin.co.kr/product/19022/41/cover500/8932473676_1.jpg',
    category: 'science',
    subcategory: 'physics',
    rating: 4.7,
    reviews: 165,
    description:
      '현대 물리학의 핵심 이론인 상대성이론을 일반인도 이해할 수 있게 설명한 책.',
    publishDate: '2023-10-18',
    publisher: '과학세계',
  },
  {
    id: 11,
    title: '프랑스 혁명사',
    author: '토마스 칼라일',
    coverImage:
      'https://image.aladin.co.kr/product/9/67/cover500/8937460351_2.jpg',
    category: 'history',
    subcategory: 'modern-history',
    rating: 4.5,
    reviews: 87,
    description:
      '프랑스 혁명의 과정과 의미를 생생하게 서술한 역사서. 시대의 격동을 실감나게 전달한다.',
    publishDate: '2023-11-05',
    publisher: '역사연구소',
  },
  {
    id: 12,
    title: '음악의 이해',
    author: '아론 코플랜드',
    coverImage:
      'https://image.aladin.co.kr/product/7865/65/cover500/8987755184_1.jpg',
    category: 'art',
    subcategory: 'music',
    rating: 4.6,
    reviews: 92,
    description:
      '음악의 기본 원리와 감상법을 설명한 고전적인 입문서. 음악을 더 깊이 이해하고 즐기는 방법을 안내한다.',
    publishDate: '2023-12-10',
    publisher: '예술출판',
  },
];
