import { Category } from '@/app/popular/components/CategoryFilter';
import { Book } from '@/components/BookCard';

// 큐레이션 카테고리 데이터
export const curationCategories: Category[] = [
  {
    id: 'all',
    name: '전체',
    color: '#E5E7EB',
    subcategories: [],
  },
  {
    id: 'classics-curation',
    name: '고전산책 큐레이션',
    color: '#D1D5DB',
    subcategories: [
      { id: 'philosophy', name: '철학' },
      { id: 'literature', name: '문학' },
      { id: 'history', name: '역사' },
      { id: 'religion', name: '종교' },
      { id: 'science', name: '과학' },
      { id: 'politics', name: '정치' },
      { id: 'economics', name: '경제' },
      { id: 'art', name: '예술' },
    ],
  },
  {
    id: 'university',
    name: '대학 추천',
    color: '#DBEAFE',
    subcategories: [
      { id: 'seoul-national', name: '서울대학교' },
      { id: 'harvard', name: '하버드 대학교' },
      { id: 'oxford', name: '옥스포드 대학교' },
      { id: 'yale', name: '예일 대학교' },
      { id: 'kyunghee', name: '경희대학교' },
    ],
  },
  {
    id: 'academy',
    name: '학술원 선정',
    color: '#FCE7F3',
    subcategories: [
      { id: 'korean-academy', name: '대한민국 학술원' },
      { id: 'french-academy', name: '프랑스 아카데미' },
      { id: 'royal-society', name: '영국 왕립학회' },
      { id: 'chinese-academy', name: '중국 학술원' },
    ],
  },
  {
    id: 'awards',
    name: '수상작',
    color: '#FFEDD5',
    subcategories: [
      { id: 'nobel', name: '노벨문학상' },
      { id: 'pulitzer', name: '퓰리처상' },
      { id: 'booker', name: '부커상' },
      { id: 'daesan', name: '대산문학상' },
    ],
  },
  {
    id: 'expert',
    name: '전문가 추천',
    color: '#ECFCCB',
    subcategories: [
      { id: 'youtube', name: '유튜버 추천' },
      { id: 'critic', name: '문학평론가 추천' },
      { id: 'philosopher', name: '철학자 추천' },
      { id: 'historian', name: '역사학자 추천' },
    ],
  },
  {
    id: 'influential',
    name: '영향력 있는 고전',
    color: '#D1FAE5',
    subcategories: [
      { id: 'political', name: '정치 사상에 영향을 준 고전' },
      { id: 'economic', name: '경제 이론에 영향을 준 고전' },
      { id: 'scientific', name: '과학 발전에 영향을 준 고전' },
      { id: 'social', name: '사회 변화에 영향을 준 고전' },
    ],
  },
  {
    id: 'theme',
    name: '특별 테마',
    color: '#FEF3C7',
    subcategories: [
      { id: 'renaissance', name: '르네상스 시대의 고전' },
      { id: 'enlightenment', name: '계몽주의 시대의 고전' },
      { id: 'modernity', name: '근대성의 탄생과 고전' },
      { id: 'existential', name: '실존주의와 현대 고전' },
    ],
  },
];

// 서울대 추천 도서
export const seoulNationalUniversityBooks: Book[] = [
  {
    id: 101,
    title: '민주주의의 수수께끼',
    author: '한나 아렌트',
    coverImage: 'https://picsum.photos/seed/book101/240/360',
    category: 'philosophy',
    subcategory: 'political-philosophy',
    rating: 4.7,
    reviews: 128,
    description:
      '정치철학의 대가가 들려주는 민주주의의 본질과 도전에 관한 통찰력 있는 분석',
    publishDate: '2018-05-12',
    publisher: '서울대학교 출판부',
  },
  {
    id: 102,
    title: '순수이성비판',
    author: '임마누엘 칸트',
    coverImage: 'https://picsum.photos/seed/book102/240/360',
    category: 'philosophy',
    subcategory: 'epistemology',
    rating: 4.5,
    reviews: 156,
    description:
      '인식론의 혁명을 가져온 칸트의 대표작으로, 인간 지식의 한계와 가능성을 탐구한다',
    publishDate: '2019-03-15',
    publisher: '학문사',
  },
  {
    id: 103,
    title: '국부론',
    author: '애덤 스미스',
    coverImage: 'https://picsum.photos/seed/book103/240/360',
    category: 'economics',
    subcategory: 'economic-theory',
    rating: 4.6,
    reviews: 143,
    description:
      '근대 경제학의 기초를 닦은 애덤 스미스의 역작. 시장 경제와 자유 무역의 원리를 설명한다',
    publishDate: '2017-08-22',
    publisher: '경제연구소',
  },
  {
    id: 104,
    title: '역사란 무엇인가',
    author: 'E.H. 카',
    coverImage: 'https://picsum.photos/seed/book104/240/360',
    category: 'history',
    subcategory: 'historiography',
    rating: 4.8,
    reviews: 178,
    description:
      '역사학의 본질과 역사가의 역할에 대한 성찰을 담은 역사철학의 고전',
    publishDate: '2016-11-10',
    publisher: '까치',
  },
  {
    id: 105,
    title: '방법서설',
    author: '르네 데카르트',
    coverImage: 'https://picsum.photos/seed/book105/240/360',
    category: 'philosophy',
    subcategory: 'modern-philosophy',
    rating: 4.4,
    reviews: 132,
    description:
      '근대 철학의 시작을 알린 데카르트의 저서로, 합리적 사고와 회의주의를 통한 진리 탐구 방법을 제시한다',
    publishDate: '2020-02-18',
    publisher: '문예출판사',
  },
  {
    id: 106,
    title: '정치경제학 비판',
    author: '카를 마르크스',
    coverImage: 'https://picsum.photos/seed/book106/240/360',
    category: 'economics',
    subcategory: 'political-economy',
    rating: 4.3,
    reviews: 112,
    description:
      '자본주의 경제의 모순을 분석하고 노동 가치론을 발전시킨 마르크스의 경제학 저서',
    publishDate: '2021-01-25',
    publisher: '서울대학교 출판부',
  },
  {
    id: 107,
    title: '고대 그리스 철학사',
    author: '프레데릭 콜린스',
    coverImage: 'https://picsum.photos/seed/book107/240/360',
    category: 'philosophy',
    subcategory: 'ancient-philosophy',
    rating: 4.6,
    reviews: 98,
    description:
      '소크라테스 이전부터 아리스토텔레스까지 그리스 철학의 발전과 사상가들을 소개하는 개론서',
    publishDate: '2019-09-12',
    publisher: '철학과사상사',
  },
  {
    id: 108,
    title: '심리학의 기초',
    author: '윌리엄 제임스',
    coverImage: 'https://picsum.photos/seed/book108/240/360',
    category: 'psychology',
    subcategory: 'general-psychology',
    rating: 4.7,
    reviews: 145,
    description:
      '현대 심리학의 기초를 정립한 윌리엄 제임스의 고전. 의식의 흐름과 실용주의 심리학을 소개한다',
    publishDate: '2018-07-30',
    publisher: '학지사',
  },
  {
    id: 109,
    title: '사회계약론',
    author: '장 자크 루소',
    coverImage: 'https://picsum.photos/seed/book109/240/360',
    category: 'philosophy',
    subcategory: 'political-philosophy',
    rating: 4.5,
    reviews: 156,
    description:
      '민주주의와 시민 사회의 기초를 제시한 루소의 대표작으로, 일반 의지와 주권 개념을 발전시켰다',
    publishDate: '2017-11-18',
    publisher: '서울대학교 출판부',
  },
  {
    id: 110,
    title: '미학 원론',
    author: '알렉산더 바움가르텐',
    coverImage: 'https://picsum.photos/seed/book110/240/360',
    category: 'philosophy',
    subcategory: 'aesthetics',
    rating: 4.2,
    reviews: 87,
    description:
      '근대 미학의 창시자로 알려진 바움가르텐의 저서로, 미학을 독립 학문으로 정립하는 기초를 마련했다',
    publishDate: '2020-04-05',
    publisher: '미학사',
  },
];

// 노벨문학상 수상작
export const nobelPrizeBooks: Book[] = [
  {
    id: 201,
    title: '백년 동안의 고독',
    author: '가브리엘 가르시아 마르케스',
    coverImage: 'https://picsum.photos/seed/book201/240/360',
    category: 'literature',
    subcategory: 'world-literature',
    rating: 4.9,
    reviews: 237,
    description:
      '라틴 아메리카 문학의 대표작으로, 부엔디아 가문의 7대에 걸친 역사를 통해 인간의 운명과 사랑, 고독을 그린 작품',
    publishDate: '1967-05-30',
    publisher: '민음사',
  },
  {
    id: 202,
    title: '어둠의 심연',
    author: '조제프 콘래드',
    coverImage: 'https://picsum.photos/seed/book202/240/360',
    category: 'literature',
    subcategory: 'classic-literature',
    rating: 4.6,
    reviews: 185,
    description:
      '제국주의와 식민지의 어두운 현실을 고발하고, 인간 내면의 악과 광기를 탐구한 소설',
    publishDate: '1899-02-15',
    publisher: '창비',
  },
  {
    id: 203,
    title: '인간조건',
    author: '앙드레 말로',
    coverImage: 'https://picsum.photos/seed/book203/240/360',
    category: 'literature',
    subcategory: 'french-literature',
    rating: 4.7,
    reviews: 142,
    description:
      '중국 혁명을 배경으로 인간의 존엄성과 혁명의 이상, 그리고 그 속에서의 인간의 고뇌를 그린 작품',
    publishDate: '1933-10-23',
    publisher: '문학과지성사',
  },
  {
    id: 204,
    title: '노인과 바다',
    author: '어니스트 헤밍웨이',
    coverImage: 'https://picsum.photos/seed/book204/240/360',
    category: 'literature',
    subcategory: 'american-literature',
    rating: 4.8,
    reviews: 215,
    description:
      '쿠바 노인 어부의 대형 청새치와의 사투를 통해 인간의 의지와 존엄성을 그린 헤밍웨이의 대표작',
    publishDate: '1952-09-01',
    publisher: '문학동네',
  },
  {
    id: 205,
    title: '서부 전선 이상 없다',
    author: '에리히 마리아 레마르크',
    coverImage: 'https://picsum.photos/seed/book205/240/360',
    category: 'literature',
    subcategory: 'war-literature',
    rating: 4.7,
    reviews: 163,
    description:
      '제1차 세계대전의 참상과 전쟁의 무의미함을 생생하게 그린 반전 소설의 고전',
    publishDate: '1929-01-31',
    publisher: '민음사',
  },
  {
    id: 206,
    title: '쉘터 스켈터',
    author: '폴 오스터',
    coverImage: 'https://picsum.photos/seed/book206/240/360',
    category: 'literature',
    subcategory: 'contemporary-literature',
    rating: 4.5,
    reviews: 124,
    description:
      '정체성의 혼란과 우연성을 탐구하는 폴 오스터의 대표작으로, 미국 현대 문학의 명작',
    publishDate: '1988-04-15',
    publisher: '열린책들',
  },
  {
    id: 207,
    title: '황야',
    author: '고레 비달',
    coverImage: 'https://picsum.photos/seed/book207/240/360',
    category: 'literature',
    subcategory: 'political-fiction',
    rating: 4.3,
    reviews: 97,
    description:
      '미국 정치의 어두운 이면과 권력의 부패를 신랄하게 비판한 정치 소설',
    publishDate: '1961-07-27',
    publisher: '문학동네',
  },
  {
    id: 208,
    title: '잃어버린 시간을 찾아서',
    author: '마르셀 프루스트',
    coverImage: 'https://picsum.photos/seed/book208/240/360',
    category: 'literature',
    subcategory: 'french-literature',
    rating: 4.9,
    reviews: 178,
    description:
      '20세기 문학의 기념비적 작품으로, 인간의 기억과 시간, 예술의 본질을 탐구한 대하소설',
    publishDate: '1913-11-14',
    publisher: '민음사',
  },
  {
    id: 209,
    title: '파우스트',
    author: '요한 볼프강 폰 괴테',
    coverImage: 'https://picsum.photos/seed/book209/240/360',
    category: 'literature',
    subcategory: 'german-literature',
    rating: 4.7,
    reviews: 145,
    description:
      '인간의 욕망과 지식 추구, 그리고 그에 따른 도덕적 갈등을 그린 독일 문학의 최고 걸작',
    publishDate: '1808-08-10',
    publisher: '창비',
  },
  {
    id: 210,
    title: '모비딕',
    author: '허먼 멜빌',
    coverImage: 'https://picsum.photos/seed/book210/240/360',
    category: 'literature',
    subcategory: 'american-literature',
    rating: 4.6,
    reviews: 189,
    description:
      '백경과 그것을 쫓는 선장 에이해브의 이야기를 통해 인간의 집착과 광기를 그린 미국 문학의 고전',
    publishDate: '1851-10-18',
    publisher: '문학동네',
  },
];

// 유튜브 채널 '책읽찌' 추천
export const youtubeBooksChannel: Book[] = [
  {
    id: 301,
    title: '군주론',
    author: '니콜로 마키아벨리',
    coverImage: 'https://picsum.photos/seed/book301/240/360',
    category: 'politics',
    subcategory: 'political-theory',
    rating: 4.6,
    reviews: 178,
    description:
      '정치 현실주의의 대표적 저서로, 권력의 획득과 유지에 관한 통찰력 있는 분석을 제공한다',
    publishDate: '1532-12-10',
    publisher: '서해문집',
  },
  {
    id: 302,
    title: '차라투스트라는 이렇게 말했다',
    author: '프리드리히 니체',
    coverImage: 'https://picsum.photos/seed/book302/240/360',
    category: 'philosophy',
    subcategory: 'existentialism',
    rating: 4.7,
    reviews: 196,
    description:
      '니체 철학의 정수를 담은 작품으로, 초인, 영원회귀, 힘에의 의지 등 그의 핵심 사상을 시적 언어로 표현한다',
    publishDate: '1883-08-15',
    publisher: '책세상',
  },
  {
    id: 303,
    title: '존재와 무',
    author: '장 폴 사르트르',
    coverImage: 'https://picsum.photos/seed/book303/240/360',
    category: 'philosophy',
    subcategory: 'existentialism',
    rating: 4.5,
    reviews: 152,
    description:
      '실존주의 철학의 대표작으로, 인간의 자유와 책임, 그리고 존재의 의미를 탐구한다',
    publishDate: '1943-06-22',
    publisher: '삼성출판사',
  },
  {
    id: 304,
    title: '국가',
    author: '플라톤',
    coverImage: 'https://picsum.photos/seed/book304/240/360',
    category: 'philosophy',
    subcategory: 'political-philosophy',
    rating: 4.8,
    reviews: 213,
    description:
      '이상적인 국가의 모습과 정의의 개념을 탐구한 플라톤의 대화편으로, 서양 정치철학의 기초를 닦았다',
    publishDate: '기원전 375년경',
    publisher: '서광사',
  },
  {
    id: 305,
    title: '공산당 선언',
    author: '카를 마르크스, 프리드리히 엥겔스',
    coverImage: 'https://picsum.photos/seed/book305/240/360',
    category: 'politics',
    subcategory: 'political-theory',
    rating: 4.4,
    reviews: 187,
    description:
      '자본주의 사회의 모순과 계급 투쟁, 그리고 공산주의 혁명의 필연성을 주장한 정치 선언문',
    publishDate: '1848-02-21',
    publisher: '돌베개',
  },
  {
    id: 306,
    title: '자유로부터의 도피',
    author: '에리히 프롬',
    coverImage: 'https://picsum.photos/seed/book306/240/360',
    category: 'psychology',
    subcategory: 'social-psychology',
    rating: 4.6,
    reviews: 142,
    description:
      '현대인의 자유에 대한 양가적 태도와 권위주의 성격의 형성 과정을 분석한 사회심리학 고전',
    publishDate: '1941-11-15',
    publisher: '책세상',
  },
  {
    id: 307,
    title: '문명의 충돌',
    author: '사무엘 헌팅턴',
    coverImage: 'https://picsum.photos/seed/book307/240/360',
    category: 'international-relations',
    subcategory: 'geopolitics',
    rating: 4.3,
    reviews: 157,
    description:
      '탈냉전 시대의 세계 질서를 문명권의 대립 구도로 분석한 국제정치학의 논쟁적 저서',
    publishDate: '1996-08-20',
    publisher: '김영사',
  },
  {
    id: 308,
    title: '역사의 종말',
    author: '프랜시스 후쿠야마',
    coverImage: 'https://picsum.photos/seed/book308/240/360',
    category: 'politics',
    subcategory: 'political-theory',
    rating: 4.2,
    reviews: 134,
    description:
      '자유민주주의의 승리와 이데올로기 대립의 종식을 선언한 냉전 종식 이후의 대표적 정치 논문',
    publishDate: '1992-05-30',
    publisher: '한울',
  },
  {
    id: 309,
    title: '조국',
    author: '토마스 만',
    coverImage: 'https://picsum.photos/seed/book309/240/360',
    category: 'literature',
    subcategory: 'german-literature',
    rating: 4.5,
    reviews: 112,
    description: '나치즘의 광기와 망명자의 비애를 그린 토마스 만의 자전적 소설',
    publishDate: '1938-10-08',
    publisher: '민음사',
  },
  {
    id: 310,
    title: '사피엔스',
    author: '유발 하라리',
    coverImage: 'https://picsum.photos/seed/book310/240/360',
    category: 'history',
    subcategory: 'world-history',
    rating: 4.8,
    reviews: 267,
    description:
      '인류의 역사를 거시적 관점에서 조망하며 인간의 본질과 문명의 발전 과정을 탐구한 베스트셀러',
    publishDate: '2011-04-25',
    publisher: '김영사',
  },
];

// 하버드 대학 수업 관련 도서
export const harvardUniversityBooks: Book[] = [
  {
    id: 401,
    title: '정의란 무엇인가',
    author: '마이클 샌델',
    coverImage: 'https://picsum.photos/seed/book401/240/360',
    category: 'philosophy',
    subcategory: 'ethics',
    rating: 4.8,
    reviews: 245,
    description:
      '하버드 대학의 인기 강의를 바탕으로 한 책으로, 정의의 개념을 다양한 철학적 관점에서 탐구한다',
    publishDate: '2009-09-15',
    publisher: '김영사',
  },
  {
    id: 402,
    title: '자본론',
    author: '카를 마르크스',
    coverImage: 'https://picsum.photos/seed/book402/240/360',
    category: 'economics',
    subcategory: 'political-economy',
    rating: 4.6,
    reviews: 178,
    description:
      '자본주의 경제 체제의 작동 원리와 모순을 분석한 마르크스의 대표작',
    publishDate: '1867-09-14',
    publisher: '비봉출판사',
  },
  {
    id: 403,
    title: '리바이어던',
    author: '토마스 홉스',
    coverImage: 'https://picsum.photos/seed/book403/240/360',
    category: 'politics',
    subcategory: 'political-theory',
    rating: 4.5,
    reviews: 163,
    description:
      '사회계약론과 절대 군주제의 필요성을 주장한 정치철학서로, 근대 정치사상의 기초를 닦았다',
    publishDate: '1651-04-20',
    publisher: '학연사',
  },
  {
    id: 404,
    title: '도덕 감정론',
    author: '애덤 스미스',
    coverImage: 'https://picsum.photos/seed/book404/240/360',
    category: 'philosophy',
    subcategory: 'ethics',
    rating: 4.7,
    reviews: 132,
    description:
      '동정심을 윤리의 기초로 삼고, 인간의 도덕적 판단과 행동의 원리를 설명한 스미스의 도덕철학서',
    publishDate: '1759-04-26',
    publisher: '비봉출판사',
  },
  {
    id: 405,
    title: '정치학',
    author: '아리스토텔레스',
    coverImage: 'https://picsum.photos/seed/book405/240/360',
    category: 'politics',
    subcategory: 'political-theory',
    rating: 4.6,
    reviews: 147,
    description:
      '국가의 본질과 목적, 이상적인 정치 체제에 대한 아리스토텔레스의 사상을 담은 고전',
    publishDate: '기원전 350년경',
    publisher: '고동출판',
  },
  {
    id: 406,
    title: '법의 정신',
    author: '몽테스키외',
    coverImage: 'https://picsum.photos/seed/book406/240/360',
    category: 'law',
    subcategory: 'political-philosophy',
    rating: 4.7,
    reviews: 124,
    description:
      '삼권분립 이론의 기초를 제시하고 법과 사회의 관계를 탐구한 정치철학의 고전',
    publishDate: '1748-06-15',
    publisher: '동서문화사',
  },
  {
    id: 407,
    title: '전쟁론',
    author: '카를 폰 클라우제비츠',
    coverImage: 'https://picsum.photos/seed/book407/240/360',
    category: 'military',
    subcategory: 'strategy',
    rating: 4.5,
    reviews: 156,
    description:
      '전쟁의 본질과 원리를 체계적으로 분석한 군사학의 고전으로, 정치와 전쟁의 관계를 정립했다',
    publishDate: '1832-11-10',
    publisher: '책세상',
  },
  {
    id: 408,
    title: '민주주의와 교육',
    author: '존 듀이',
    coverImage: 'https://picsum.photos/seed/book408/240/360',
    category: 'education',
    subcategory: 'philosophy-of-education',
    rating: 4.8,
    reviews: 187,
    description:
      '교육의 사회적 역할과 민주주의 발전에 있어 교육의 중요성을 강조한 교육철학의 명저',
    publishDate: '1916-05-26',
    publisher: '학지사',
  },
  {
    id: 409,
    title: '무지의 베일',
    author: '존 롤스',
    coverImage: 'https://picsum.photos/seed/book409/240/360',
    category: 'philosophy',
    subcategory: 'ethics',
    rating: 4.6,
    reviews: 145,
    description:
      '사회 정의의 원칙을 도출하기 위한 롤스의 정의론으로, 공정으로서의 정의 개념을 제시한다',
    publishDate: '1971-03-22',
    publisher: '창비',
  },
  {
    id: 410,
    title: '경제학 원론',
    author: '그레고리 맨큐',
    coverImage: 'https://picsum.photos/seed/book410/240/360',
    category: 'economics',
    subcategory: 'microeconomics',
    rating: 4.8,
    reviews: 234,
    description:
      '하버드 대학 경제학과의 인기 강의를 바탕으로 한 경제학 입문서로, 현대 경제학의 기초 원리를 설명한다',
    publishDate: '1997-02-10',
    publisher: '시그마프레스',
  },
];

// 대한민국 학술원 선정 고전
export const koreanAcademyBooks: Book[] = [
  {
    id: 501,
    title: '논어',
    author: '공자',
    coverImage: 'https://picsum.photos/seed/book501/240/360',
    category: 'philosophy',
    subcategory: 'confucianism',
    rating: 4.9,
    reviews: 213,
    description:
      '공자와 제자들의 대화를 통해 유교의 핵심 가치와 도덕, 정치 이념을 전달하는 동양 고전',
    publishDate: '기원전 500년경',
    publisher: '을유문화사',
  },
  {
    id: 502,
    title: '맹자',
    author: '맹자',
    coverImage: 'https://picsum.photos/seed/book502/240/360',
    category: 'philosophy',
    subcategory: 'confucianism',
    rating: 4.7,
    reviews: 178,
    description:
      '유교의 인성론과 정치사상을 발전시킨 맹자의 사상을 담은 유교 경전',
    publishDate: '기원전 300년경',
    publisher: '동서문화사',
  },
  {
    id: 503,
    title: '삼국사기',
    author: '김부식',
    coverImage: 'https://picsum.photos/seed/book503/240/360',
    category: 'history',
    subcategory: 'korean-history',
    rating: 4.8,
    reviews: 156,
    description:
      '고려 시대에 편찬된 우리나라 최초의 관찬 역사서로, 삼국 시대의 역사를 기록한 귀중한 사료',
    publishDate: '1145년',
    publisher: '한국고전번역원',
  },
  {
    id: 504,
    title: '주역',
    author: '불명',
    coverImage: 'https://picsum.photos/seed/book504/240/360',
    category: 'philosophy',
    subcategory: 'ancient-philosophy',
    rating: 4.6,
    reviews: 145,
    description:
      '음양의 변화 원리와 64괘를 통해 우주의 운행 법칙과 인간 삶의 지혜를 담은 동양 고전',
    publishDate: '기원전 1000년경',
    publisher: '명문당',
  },
  {
    id: 505,
    title: '택리지',
    author: '이중환',
    coverImage: 'https://picsum.photos/seed/book505/240/360',
    category: 'geography',
    subcategory: 'human-geography',
    rating: 4.5,
    reviews: 128,
    description:
      '조선 후기에 저술된 인문지리서로, 살기 좋은 땅을 고르는 기준과 조선의 지리를 설명한 고전',
    publishDate: '1751년',
    publisher: '을유문화사',
  },
  {
    id: 506,
    title: '동의보감',
    author: '허준',
    coverImage: 'https://picsum.photos/seed/book506/240/360',
    category: 'medicine',
    subcategory: 'traditional-medicine',
    rating: 4.8,
    reviews: 167,
    description:
      '조선 시대 최고의 의학서로, 한의학 지식을 체계적으로 정리한 백과사전식 의서',
    publishDate: '1613년',
    publisher: '한국고전번역원',
  },
  {
    id: 507,
    title: '훈민정음',
    author: '세종대왕',
    coverImage: 'https://picsum.photos/seed/book507/240/360',
    category: 'linguistics',
    subcategory: 'korean-language',
    rating: 5.0,
    reviews: 214,
    description:
      '한글 창제의 원리와 사용법을 설명한 역사적 문헌으로, 유네스코 세계기록유산에 등재되었다',
    publishDate: '1446년',
    publisher: '한국학중앙연구원',
  },
  {
    id: 508,
    title: '이륜행실도',
    author: '김안국',
    coverImage: 'https://picsum.photos/seed/book508/240/360',
    category: 'ethics',
    subcategory: 'confucian-ethics',
    rating: 4.4,
    reviews: 98,
    description: '유교적 인륜도덕을 그림과 함께 설명한 조선 시대의 윤리 교과서',
    publishDate: '1518년',
    publisher: '국학자료원',
  },
  {
    id: 509,
    title: '성학집요',
    author: '이이',
    coverImage: 'https://picsum.photos/seed/book509/240/360',
    category: 'philosophy',
    subcategory: 'neo-confucianism',
    rating: 4.7,
    reviews: 123,
    description:
      '조선 성리학의 대가 이이(율곡)가 저술한 성리학 입문서로, 수양과 통치의 원리를 설명한다',
    publishDate: '1575년',
    publisher: '한길사',
  },
  {
    id: 510,
    title: '무예도보통지',
    author: '이덕형',
    coverImage: 'https://picsum.photos/seed/book510/240/360',
    category: 'martial-arts',
    subcategory: 'korean-martial-arts',
    rating: 4.6,
    reviews: 145,
    description:
      '조선 시대 무예를 체계적으로 정리한 병서로, 다양한 무기와 격투술을 도해와 함께 설명했다',
    publishDate: '1790년',
    publisher: '동문선',
  },
];

// 프랑스 아카데미 선정 작품
export const frenchAcademyBooks: Book[] = [
  {
    id: 601,
    title: '인간 조건',
    author: '앙드레 말로',
    coverImage: 'https://picsum.photos/seed/book601/240/360',
    category: 'literature',
    subcategory: 'french-literature',
    rating: 4.7,
    reviews: 168,
    description:
      '1920년대 상하이 혁명을 배경으로 인간의 존재 의미와 혁명의 비극을 그린 걸작',
    publishDate: '1933-10-23',
    publisher: '문학과지성사',
  },
  {
    id: 602,
    title: '이방인',
    author: '알베르 카뮈',
    coverImage: 'https://picsum.photos/seed/book602/240/360',
    category: 'literature',
    subcategory: 'french-literature',
    rating: 4.8,
    reviews: 212,
    description:
      '부조리한 세계와 실존적 허무를 그린 카뮈의 대표작으로, 실존주의 문학의 정수를 보여준다',
    publishDate: '1942-05-19',
    publisher: '열린책들',
  },
  {
    id: 603,
    title: '서부 전선 이상 없다',
    author: '에리히 마리아 레마르크',
    coverImage: 'https://picsum.photos/seed/book603/240/360',
    category: 'literature',
    subcategory: 'war-literature',
    rating: 4.9,
    reviews: 245,
    description:
      '제1차 세계대전의 참상과 전쟁의 무의미함을 그린 반전 소설로, 전쟁의 실상을 생생하게 전달한다',
    publishDate: '1929-01-31',
    publisher: '민음사',
  },
  {
    id: 604,
    title: '적과 흑',
    author: '스탕달',
    coverImage: 'https://picsum.photos/seed/book604/240/360',
    category: 'literature',
    subcategory: 'french-literature',
    rating: 4.6,
    reviews: 178,
    description:
      '프랑스 왕정복고 시대를 배경으로 야심 많은 청년의 사랑과 출세를 그린 심리 소설',
    publishDate: '1830-11-13',
    publisher: '문학동네',
  },
  {
    id: 605,
    title: '페스트',
    author: '알베르 카뮈',
    coverImage: 'https://picsum.photos/seed/book605/240/360',
    category: 'literature',
    subcategory: 'french-literature',
    rating: 4.7,
    reviews: 187,
    description:
      '알제리의 한 도시를 덮친 페스트를 통해 인간의 연대와 저항 정신을 그린 우화적 소설',
    publishDate: '1947-06-10',
    publisher: '민음사',
  },
  {
    id: 606,
    title: '레 미제라블',
    author: '빅토르 위고',
    coverImage: 'https://picsum.photos/seed/book606/240/360',
    category: 'literature',
    subcategory: 'french-literature',
    rating: 4.9,
    reviews: 276,
    description:
      '19세기 프랑스 사회를 배경으로 장 발장의 구원과 성장을 그린 세계 문학의 걸작',
    publishDate: '1862-04-03',
    publisher: '민음사',
  },
  {
    id: 607,
    title: '마담 보바리',
    author: '귀스타브 플로베르',
    coverImage: 'https://picsum.photos/seed/book607/240/360',
    category: 'literature',
    subcategory: 'french-literature',
    rating: 4.8,
    reviews: 192,
    description:
      '현실과 이상의 괴리 속에서 불행한 삶을 살다 파멸하는 한 여인의 이야기를 통해 19세기 프랑스 부르주아 사회를 비판한 소설',
    publishDate: '1857-12-15',
    publisher: '문학동네',
  },
  {
    id: 608,
    title: '말과 사물',
    author: '미셸 푸코',
    coverImage: 'https://picsum.photos/seed/book608/240/360',
    category: 'philosophy',
    subcategory: 'french-philosophy',
    rating: 4.6,
    reviews: 156,
    description:
      '지식의 고고학을 통해 서구 지식 체계의 역사적 변천을 분석한 구조주의 철학의 명저',
    publishDate: '1966-05-17',
    publisher: '민음사',
  },
  {
    id: 609,
    title: '보바리 씨',
    author: '귀스타브 플로베르',
    coverImage: 'https://picsum.photos/seed/book609/240/360',
    category: 'literature',
    subcategory: 'french-literature',
    rating: 4.5,
    reviews: 134,
    description:
      '마담 보바리의 남편 샤를 보바리의 시각에서 본 프랑스 지방의 일상과 배신, 사랑의 이야기',
    publishDate: '1856-10-01',
    publisher: '창비',
  },
  {
    id: 610,
    title: '존재와 시간',
    author: '마르틴 하이데거',
    coverImage: 'https://picsum.photos/seed/book610/240/360',
    category: 'philosophy',
    subcategory: 'existentialism',
    rating: 4.7,
    reviews: 174,
    description:
      '인간 존재(Dasein)의 본질적 구조와 시간성을 분석한 20세기 철학의 기념비적 저작',
    publishDate: '1927-02-28',
    publisher: '문학과지성사',
  },
];

// 분기별 고전
export const quarterlyClassicsBooks: Book[] = [
  {
    id: 701,
    title: '국가',
    author: '플라톤',
    coverImage: 'https://picsum.photos/seed/book701/240/360',
    category: 'philosophy',
    subcategory: 'political-philosophy',
    rating: 4.9,
    reviews: 210,
    description: '정의로운 국가와 개인의 관계에 대한 철학적 탐구의 고전',
    publishDate: '기원전 375년경',
    publisher: '고전산책',
  },
  {
    id: 702,
    title: '군주론',
    author: '니콜로 마키아벨리',
    coverImage: 'https://picsum.photos/seed/book702/240/360',
    category: 'politics',
    subcategory: 'political-theory',
    rating: 4.7,
    reviews: 185,
    description:
      '정치 현실주의의 대표작으로, 권력의 본질과 통치 원리를 탐구한다',
    publishDate: '1532년',
    publisher: '고전산책',
  },
  {
    id: 703,
    title: '성서',
    author: '여러 저자',
    coverImage: 'https://picsum.photos/seed/book703/240/360',
    category: 'religion',
    subcategory: 'christianity',
    rating: 4.9,
    reviews: 320,
    description:
      '기독교의 경전으로, 서양 문명의 형성과 발전에 지대한 영향을 미친 고전',
    publishDate: '다양한 시기',
    publisher: '고전산책',
  },
  {
    id: 704,
    title: '변신',
    author: '프란츠 카프카',
    coverImage: 'https://picsum.photos/seed/book704/240/360',
    category: 'literature',
    subcategory: 'modern-literature',
    rating: 4.8,
    reviews: 198,
    description:
      '현대 문학의 상징적 작품으로, 인간 소외와 실존의 문제를 다룬 카프카의 대표작',
    publishDate: '1915년',
    publisher: '고전산책',
  },
  {
    id: 705,
    title: '일리아스',
    author: '호메로스',
    coverImage: 'https://picsum.photos/seed/book705/240/360',
    category: 'literature',
    subcategory: 'epic-poetry',
    rating: 4.7,
    reviews: 176,
    description: '트로이 전쟁을 배경으로 한 서양 문학의 원천이 되는 서사시',
    publishDate: '기원전 8세기경',
    publisher: '고전산책',
  },
  {
    id: 706,
    title: '이성비판',
    author: '칸트',
    coverImage: 'https://picsum.photos/seed/book706/240/360',
    category: 'philosophy',
    subcategory: 'metaphysics',
    rating: 4.6,
    reviews: 154,
    description: '서양 철학의 인식론적 전환을 가져온 칸트의 대표작',
    publishDate: '1781년',
    publisher: '고전산책',
  },
  {
    id: 707,
    title: '사회계약론',
    author: '장 자크 루소',
    coverImage: 'https://picsum.photos/seed/book707/240/360',
    category: 'philosophy',
    subcategory: 'political-philosophy',
    rating: 4.7,
    reviews: 165,
    description: '민주주의 이론의 기초를 제공한 루소의 대표적 정치철학서',
    publishDate: '1762년',
    publisher: '고전산책',
  },
  {
    id: 708,
    title: '도덕경',
    author: '노자',
    coverImage: 'https://picsum.photos/seed/book708/240/360',
    category: 'philosophy',
    subcategory: 'eastern-philosophy',
    rating: 4.8,
    reviews: 187,
    description:
      '도가 사상의 핵심을 담은 중국 고전으로, 자연과 조화를 이루는 삶의 지혜를 설파한다',
    publishDate: '기원전 6세기경',
    publisher: '고전산책',
  },
];

// 이달의 고전
export const monthlyClassicsBooks: Book[] = [
  {
    id: 711,
    title: '안티고네',
    author: '소포클레스',
    coverImage: 'https://picsum.photos/seed/book711/240/360',
    category: 'literature',
    subcategory: 'greek-tragedy',
    rating: 4.7,
    reviews: 168,
    description: '개인의 양심과 국가 법률 사이의 갈등을 다룬 고대 그리스 비극',
    publishDate: '기원전 441년경',
    publisher: '고전산책',
  },
  {
    id: 712,
    title: '파우스트',
    author: '요한 볼프강 폰 괴테',
    coverImage: 'https://picsum.photos/seed/book712/240/360',
    category: 'literature',
    subcategory: 'german-literature',
    rating: 4.8,
    reviews: 192,
    description: '인간의 욕망과 구원에 관한 독일 문학의 대표작',
    publishDate: '1829년',
    publisher: '고전산책',
  },
  {
    id: 713,
    title: '방법서설',
    author: '르네 데카르트',
    coverImage: 'https://picsum.photos/seed/book713/240/360',
    category: 'philosophy',
    subcategory: 'epistemology',
    rating: 4.6,
    reviews: 157,
    description:
      '근대 철학의 출발점으로 여겨지는 저서로, 방법적 회의와 합리주의의 기초를 세웠다',
    publishDate: '1637년',
    publisher: '고전산책',
  },
  {
    id: 714,
    title: '논어',
    author: '공자',
    coverImage: 'https://picsum.photos/seed/book714/240/360',
    category: 'philosophy',
    subcategory: 'confucianism',
    rating: 4.9,
    reviews: 215,
    description:
      '공자와 제자들의 대화를 통해 유교 사상의 핵심을 전달하는 동양 고전',
    publishDate: '기원전 5세기경',
    publisher: '고전산책',
  },
  {
    id: 715,
    title: '햄릿',
    author: '윌리엄 셰익스피어',
    coverImage: 'https://picsum.photos/seed/book715/240/360',
    category: 'literature',
    subcategory: 'english-drama',
    rating: 4.9,
    reviews: 230,
    description: '복수와 실존적 고뇌를 다룬 셰익스피어의 대표적 비극',
    publishDate: '1600년경',
    publisher: '고전산책',
  },
];

// 편집자 선정
export const editorsChoiceBooks: Book[] = [
  {
    id: 721,
    title: '카라마조프가의 형제들',
    author: '표도르 도스토예프스키',
    coverImage: 'https://picsum.photos/seed/book721/240/360',
    category: 'literature',
    subcategory: 'russian-literature',
    rating: 4.9,
    reviews: 223,
    description:
      '신의 존재, 도덕, 자유 의지 등 깊은 철학적 주제를 다룬 도스토예프스키의 최고 걸작',
    publishDate: '1880년',
    publisher: '고전산책',
  },
  {
    id: 722,
    title: '자본론',
    author: '카를 마르크스',
    coverImage: 'https://picsum.photos/seed/book722/240/360',
    category: 'economics',
    subcategory: 'political-economy',
    rating: 4.7,
    reviews: 187,
    description: '자본주의 경제 체제의 근본적 분석과 비판을 담은 경제학의 고전',
    publishDate: '1867년',
    publisher: '고전산책',
  },
  {
    id: 723,
    title: '오디세이아',
    author: '호메로스',
    coverImage: 'https://picsum.photos/seed/book723/240/360',
    category: 'literature',
    subcategory: 'epic-poetry',
    rating: 4.8,
    reviews: 196,
    description:
      '트로이 전쟁 영웅 오디세우스의 귀향 여정을 그린 서양 문학의 원형',
    publishDate: '기원전 8세기경',
    publisher: '고전산책',
  },
  {
    id: 724,
    title: '리바이어던',
    author: '토마스 홉스',
    coverImage: 'https://picsum.photos/seed/book724/240/360',
    category: 'philosophy',
    subcategory: 'political-philosophy',
    rating: 4.6,
    reviews: 162,
    description: '국가의 기원과 정당성에 관한 고전적 논의를 담은 정치철학서',
    publishDate: '1651년',
    publisher: '고전산책',
  },
  {
    id: 725,
    title: '전쟁론',
    author: '카를 폰 클라우제비츠',
    coverImage: 'https://picsum.photos/seed/book725/240/360',
    category: 'military',
    subcategory: 'military-strategy',
    rating: 4.7,
    reviews: 174,
    description: '근대 군사 이론의 기초를 확립한 클라우제비츠의 대표작',
    publishDate: '1832년',
    publisher: '고전산책',
  },
];

// 고전 입문자를 위한 선택
export const beginnerClassicsBooks: Book[] = [
  {
    id: 731,
    title: '소크라테스의 변명',
    author: '플라톤',
    coverImage: 'https://picsum.photos/seed/book731/240/360',
    category: 'philosophy',
    subcategory: 'ancient-philosophy',
    rating: 4.8,
    reviews: 189,
    description:
      '소크라테스의 재판과 변론을 기록한 플라톤의 대화편으로, 철학적 질문의 본질을 보여준다',
    publishDate: '기원전 399년경',
    publisher: '고전산책',
  },
  {
    id: 732,
    title: '노인과 바다',
    author: '어니스트 헤밍웨이',
    coverImage: 'https://picsum.photos/seed/book732/240/360',
    category: 'literature',
    subcategory: 'american-literature',
    rating: 4.7,
    reviews: 201,
    description: '인간의 의지와 자연의 대결을 그린 헤밍웨이의 간결한 걸작',
    publishDate: '1952년',
    publisher: '고전산책',
  },
  {
    id: 733,
    title: '동물농장',
    author: '조지 오웰',
    coverImage: 'https://picsum.photos/seed/book733/240/360',
    category: 'literature',
    subcategory: 'political-satire',
    rating: 4.8,
    reviews: 214,
    description: '전체주의와 권력의 부패를 풍자한 우화 소설',
    publishDate: '1945년',
    publisher: '고전산책',
  },
  {
    id: 734,
    title: '데미안',
    author: '헤르만 헤세',
    coverImage: 'https://picsum.photos/seed/book734/240/360',
    category: 'literature',
    subcategory: 'bildungsroman',
    rating: 4.6,
    reviews: 176,
    description: '자아 발견과 정신적 성장의 여정을 그린 헤세의 대표작',
    publishDate: '1919년',
    publisher: '고전산책',
  },
  {
    id: 735,
    title: '이솝 우화',
    author: '이솝',
    coverImage: 'https://picsum.photos/seed/book735/240/360',
    category: 'literature',
    subcategory: 'fables',
    rating: 4.7,
    reviews: 183,
    description: '짧지만 깊은 교훈을 담은 서양 우화의 원형',
    publishDate: '기원전 6세기경',
    publisher: '고전산책',
  },
];

// 필수 고전 모음
export const essentialClassicsBooks: Book[] = [
  {
    id: 741,
    title: '전쟁과 평화',
    author: '레프 톨스토이',
    coverImage: 'https://picsum.photos/seed/book741/240/360',
    category: 'literature',
    subcategory: 'russian-literature',
    rating: 4.9,
    reviews: 245,
    description:
      '나폴레옹 전쟁 시기 러시아 사회를 배경으로 한 방대한 역사 소설',
    publishDate: '1869년',
    publisher: '고전산책',
  },
  {
    id: 742,
    title: '대학',
    author: '공자 문하',
    coverImage: 'https://picsum.photos/seed/book742/240/360',
    category: 'philosophy',
    subcategory: 'confucianism',
    rating: 4.7,
    reviews: 172,
    description:
      '유교 사상의 핵심을 담은 사서 중 하나로, 개인 수양과 정치의 원리를 설명한다',
    publishDate: '기원전 5세기경',
    publisher: '고전산책',
  },
  {
    id: 743,
    title: '시민 불복종',
    author: '헨리 데이비드 소로',
    coverImage: 'https://picsum.photos/seed/book743/240/360',
    category: 'philosophy',
    subcategory: 'political-philosophy',
    rating: 4.6,
    reviews: 158,
    description:
      '개인의 양심과 국가 권위 사이의 관계를 탐구한 미국 초월주의의 대표작',
    publishDate: '1849년',
    publisher: '고전산책',
  },
  {
    id: 744,
    title: '고백록',
    author: '아우구스티누스',
    coverImage: 'https://picsum.photos/seed/book744/240/360',
    category: 'religion',
    subcategory: 'christian-philosophy',
    rating: 4.8,
    reviews: 187,
    description:
      '기독교 사상가 아우구스티누스의 자전적 저서로, 종교적 회심과 신앙의 여정을 그렸다',
    publishDate: '400년경',
    publisher: '고전산책',
  },
  {
    id: 745,
    title: '국부론',
    author: '애덤 스미스',
    coverImage: 'https://picsum.photos/seed/book745/240/360',
    category: 'economics',
    subcategory: 'classical-economics',
    rating: 4.7,
    reviews: 194,
    description:
      '현대 경제학의 기초를 세운 애덤 스미스의 대표작으로, 자유 시장 경제의 원리를 설명했다',
    publishDate: '1776년',
    publisher: '고전산책',
  },
];

// 카테고리별 고전 도서 모음
export const philosophyClassicsBooks = quarterlyClassicsBooks
  .filter(book => book.category === 'philosophy')
  .concat(
    monthlyClassicsBooks.filter(book => book.category === 'philosophy'),
    editorsChoiceBooks.filter(book => book.category === 'philosophy'),
    beginnerClassicsBooks.filter(book => book.category === 'philosophy')
  );

export const literatureClassicsBooks = quarterlyClassicsBooks
  .filter(book => book.category === 'literature')
  .concat(
    monthlyClassicsBooks.filter(book => book.category === 'literature'),
    editorsChoiceBooks.filter(book => book.category === 'literature'),
    beginnerClassicsBooks.filter(book => book.category === 'literature')
  );

export const historyClassicsBooks = [
  ...quarterlyClassicsBooks.filter(book => book.category === 'history'),
  ...monthlyClassicsBooks.filter(book => book.category === 'history'),
  ...editorsChoiceBooks.filter(book => book.category === 'history'),
  ...beginnerClassicsBooks.filter(book => book.category === 'history'),
  ...essentialClassicsBooks.filter(book => book.category === 'history'),
  {
    id: 801,
    title: '역사의 연구',
    author: '아놀드 토인비',
    coverImage: 'https://picsum.photos/seed/book801/240/360',
    category: 'history',
    subcategory: 'world-history',
    rating: 4.7,
    reviews: 178,
    description: '인류 문명의 발생과 발전, 쇠퇴의 패턴을 분석한 역사학의 고전',
    publishDate: '1934년',
    publisher: '고전산책',
  },
  {
    id: 802,
    title: '로마인 이야기',
    author: '시오노 나나미',
    coverImage: 'https://picsum.photos/seed/book802/240/360',
    category: 'history',
    subcategory: 'ancient-rome',
    rating: 4.9,
    reviews: 212,
    description:
      '고대 로마의 탄생부터 몰락까지의 과정을 생생하게 서술한 역사서',
    publishDate: '1992년',
    publisher: '고전산책',
  },
];

export const religionClassicsBooks = [
  ...quarterlyClassicsBooks.filter(book => book.category === 'religion'),
  ...monthlyClassicsBooks.filter(book => book.category === 'religion'),
  ...editorsChoiceBooks.filter(book => book.category === 'religion'),
  ...beginnerClassicsBooks.filter(book => book.category === 'religion'),
  ...essentialClassicsBooks.filter(book => book.category === 'religion'),
  {
    id: 811,
    title: '불교철학',
    author: '스티븐 배철러',
    coverImage: 'https://picsum.photos/seed/book811/240/360',
    category: 'religion',
    subcategory: 'buddhism',
    rating: 4.6,
    reviews: 145,
    description: '불교 사상의 핵심 개념과 발전 과정을 체계적으로 설명한 개론서',
    publishDate: '2010년',
    publisher: '고전산책',
  },
  {
    id: 812,
    title: '유대교의 역사',
    author: '마틴 굿맨',
    coverImage: 'https://picsum.photos/seed/book812/240/360',
    category: 'religion',
    subcategory: 'judaism',
    rating: 4.5,
    reviews: 134,
    description:
      '세계 최초의 유일신 종교의 기원과 발전 과정을 통찰력 있게 분석한 책',
    publishDate: '2005년',
    publisher: '고전산책',
  },
];

export const scienceClassicsBooks = [
  {
    id: 821,
    title: '종의 기원',
    author: '찰스 다윈',
    coverImage: 'https://picsum.photos/seed/book821/240/360',
    category: 'science',
    subcategory: 'biology',
    rating: 4.9,
    reviews: 210,
    description: '진화론의 기초를 확립한 다윈의 혁명적 저서',
    publishDate: '1859년',
    publisher: '고전산책',
  },
  {
    id: 822,
    title: '상대성 이론',
    author: '알베르트 아인슈타인',
    coverImage: 'https://picsum.photos/seed/book822/240/360',
    category: 'science',
    subcategory: 'physics',
    rating: 4.8,
    reviews: 187,
    description:
      '현대 물리학의 기초가 된 아인슈타인의 혁명적 이론을 설명한 원전',
    publishDate: '1916년',
    publisher: '고전산책',
  },
  {
    id: 823,
    title: '수학의 원리',
    author: '버트런드 러셀',
    coverImage: 'https://picsum.photos/seed/book823/240/360',
    category: 'science',
    subcategory: 'mathematics',
    rating: 4.7,
    reviews: 156,
    description: '수학의 논리적 기초를 정립하려 한 20세기 초의 기념비적 저작',
    publishDate: '1910년',
    publisher: '고전산책',
  },
];

export const politicsClassicsBooks = [
  ...quarterlyClassicsBooks.filter(book => book.category === 'politics'),
  ...monthlyClassicsBooks.filter(book => book.category === 'politics'),
  ...editorsChoiceBooks.filter(book => book.category === 'politics'),
  ...beginnerClassicsBooks.filter(book => book.category === 'politics'),
  ...essentialClassicsBooks.filter(book => book.category === 'politics'),
  {
    id: 831,
    title: '정치학',
    author: '아리스토텔레스',
    coverImage: 'https://picsum.photos/seed/book831/240/360',
    category: 'politics',
    subcategory: 'political-philosophy',
    rating: 4.8,
    reviews: 192,
    description:
      '서양 정치 이론의 기초를 닦은 아리스토텔레스의 대표적 정치 철학서',
    publishDate: '기원전 4세기',
    publisher: '고전산책',
  },
];

export const economicsClassicsBooks = [
  ...quarterlyClassicsBooks.filter(book => book.category === 'economics'),
  ...monthlyClassicsBooks.filter(book => book.category === 'economics'),
  ...editorsChoiceBooks.filter(book => book.category === 'economics'),
  ...beginnerClassicsBooks.filter(book => book.category === 'economics'),
  ...essentialClassicsBooks.filter(book => book.category === 'economics'),
  {
    id: 841,
    title: '경제학의 원리',
    author: '알프레드 마샬',
    coverImage: 'https://picsum.photos/seed/book841/240/360',
    category: 'economics',
    subcategory: 'economics-theory',
    rating: 4.6,
    reviews: 148,
    description: '근대 경제학의 체계를 정립한 마샬의 대표작',
    publishDate: '1890년',
    publisher: '고전산책',
  },
];

export const artClassicsBooks = [
  {
    id: 851,
    title: '예술의 역사',
    author: '에른스트 곰브리치',
    coverImage: 'https://picsum.photos/seed/book851/240/360',
    category: 'art',
    subcategory: 'art-history',
    rating: 4.9,
    reviews: 205,
    description: '선사 시대부터 현대까지 미술의 역사를 통찰력 있게 정리한 명저',
    publishDate: '1950년',
    publisher: '고전산책',
  },
  {
    id: 852,
    title: '미학이란 무엇인가',
    author: '모리스 베르되브스키',
    coverImage: 'https://picsum.photos/seed/book852/240/360',
    category: 'art',
    subcategory: 'aesthetics',
    rating: 4.7,
    reviews: 167,
    description: '예술과 미의 본질에 관한 철학적 탐구',
    publishDate: '1974년',
    publisher: '고전산책',
  },
];

// 컬렉션을 모두 모아서 관리에 새로운 큐레이션 컬렉션 추가
export const allCollections = {
  // 고전산책 큐레이션 카테고리별 컬렉션
  philosophy: {
    id: 'philosophy',
    title: '고전산책 큐레이션: 철학 고전',
    books: philosophyClassicsBooks,
    category: 'classics-curation',
  },
  literature: {
    id: 'literature',
    title: '고전산책 큐레이션: 문학 고전',
    books: literatureClassicsBooks,
    category: 'classics-curation',
  },
  history: {
    id: 'history',
    title: '고전산책 큐레이션: 역사 고전',
    books: historyClassicsBooks,
    category: 'classics-curation',
  },
  religion: {
    id: 'religion',
    title: '고전산책 큐레이션: 종교 고전',
    books: religionClassicsBooks,
    category: 'classics-curation',
  },
  science: {
    id: 'science',
    title: '고전산책 큐레이션: 과학 고전',
    books: scienceClassicsBooks,
    category: 'classics-curation',
  },
  politics: {
    id: 'politics',
    title: '고전산책 큐레이션: 정치 고전',
    books: politicsClassicsBooks,
    category: 'classics-curation',
  },
  economics: {
    id: 'economics',
    title: '고전산책 큐레이션: 경제 고전',
    books: economicsClassicsBooks,
    category: 'classics-curation',
  },
  art: {
    id: 'art',
    title: '고전산책 큐레이션: 예술 고전',
    books: artClassicsBooks,
    category: 'classics-curation',
  },

  // 기존 컬렉션
  'quarterly-classics': {
    id: 'quarterly-classics',
    title: '분기별 고전',
    books: quarterlyClassicsBooks,
    category: 'quarterly',
  },
  'monthly-classics': {
    id: 'monthly-classics',
    title: '이달의 고전',
    books: monthlyClassicsBooks,
    category: 'monthly',
  },
  'editors-choice': {
    id: 'editors-choice',
    title: '편집자 선정',
    books: editorsChoiceBooks,
    category: 'editors',
  },
  'beginner-classics': {
    id: 'beginner-classics',
    title: '고전 입문자를 위한 선택',
    books: beginnerClassicsBooks,
    category: 'beginner',
  },
  'essential-classics': {
    id: 'essential-classics',
    title: '필수 고전 모음',
    books: essentialClassicsBooks,
    category: 'essential',
  },
  'seoul-national': {
    id: 'seoul-national',
    title: '서울대학교 인문학부 추천 도서',
    books: seoulNationalUniversityBooks,
    category: 'university',
  },
  harvard: {
    id: 'harvard',
    title: '하버드 대학 수업 관련 도서',
    books: harvardUniversityBooks,
    category: 'university',
  },
  nobel: {
    id: 'nobel',
    title: '노벨문학상 수상작',
    books: nobelPrizeBooks,
    category: 'awards',
  },
  youtube: {
    id: 'youtube',
    title: "유튜브 채널 '책읽찌' 추천",
    books: youtubeBooksChannel,
    category: 'expert',
  },
  'korean-academy': {
    id: 'korean-academy',
    title: '대한민국 학술원 선정 고전',
    books: koreanAcademyBooks,
    category: 'academy',
  },
  'french-academy': {
    id: 'french-academy',
    title: '프랑스 아카데미 선정 작품',
    books: frenchAcademyBooks,
    category: 'academy',
  },
};

// 모든 도서를 담는 배열 (검색이나 필터링에 사용)
export const allBooks: Book[] = [
  ...quarterlyClassicsBooks,
  ...monthlyClassicsBooks,
  ...editorsChoiceBooks,
  ...beginnerClassicsBooks,
  ...essentialClassicsBooks,
  ...seoulNationalUniversityBooks,
  ...nobelPrizeBooks,
  ...youtubeBooksChannel,
  ...harvardUniversityBooks,
  ...koreanAcademyBooks,
  ...frenchAcademyBooks,
  // 직접 추가한 카테고리별 책들
  ...historyClassicsBooks.filter(book => book.id >= 801),
  ...religionClassicsBooks.filter(book => book.id >= 811),
  ...scienceClassicsBooks,
  ...politicsClassicsBooks.filter(book => book.id >= 831),
  ...economicsClassicsBooks.filter(book => book.id >= 841),
  ...artClassicsBooks,
];
